import type { FastifyInstance } from "fastify";
import { authRoutes } from "./auth/index.js";
import { patientRoutes } from "./patients/index.js";
import { appointmentRoutes } from "./appointments/index.js";
import { campaignRoutes } from "./campaigns/index.js";
import { dashboardRoutes } from "./dashboard/index.js";
import { whatsappWebhookRoutes } from "./webhooks/whatsapp.js";
import { stripeWebhookRoutes } from "./webhooks/stripe.js";
import { mercadoPagoWebhookRoutes } from "./webhooks/mercadopago.js";
import { medicalHistoryRoutes } from "./clinical/medical-history.js";
import { odontogramRoutes } from "./clinical/odontogram.js";
import { treatmentPlanRoutes } from "./clinical/treatment-plan.js";
import { visitNotesRoutes } from "./clinical/visit-notes.js";
import { periodontogramRoutes } from "./clinical/periodontogram.js";
import { prescriptionRoutes } from "./clinical/prescriptions.js";
import { consentRoutes } from "./clinical/consents.js";
import { evolutionTemplateRoutes } from "./clinical/evolution-templates.js";
import { medicalHistoryAuditRoutes } from "./clinical/medical-history-audit.js";
import { patientSummaryRoutes } from "./clinical/patient-summary.js";
import { odontogramVersionRoutes } from "./clinical/odontogram-versions.js";
import { periodontogramVersionRoutes } from "./clinical/periodontogram-versions.js";
import { patientImageRoutes } from "./clinical/patient-images.js";
import { plaqueRecordRoutes } from "./clinical/plaque-records.js";
import { agendaRoutes } from "./agenda/index.js";
import { googleCalendarRoutes } from "./google-calendar/index.js";
import { configuracionRoutes } from "./configuracion/index.js";
import { dentistRoutes } from "./dentists/index.js";
import { treatmentTypeRoutes } from "./treatment-types/index.js";
import { chairRoutes } from "./chairs/index.js";
import { pipelineRoutes } from "./pipeline/index.js";
import { conversationRoutes } from "./conversations/index.js";
import { adminRoutes } from "./admin/index.js";
import { whatsappRoutes } from "./whatsapp/index.js";
import { whatsappTemplateRoutes } from "./whatsapp-templates/index.js";
import { notificationRoutes } from "./notifications/index.js";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(authRoutes);
  await app.register(dashboardRoutes);
  await app.register(patientRoutes);
  await app.register(appointmentRoutes);
  await app.register(campaignRoutes);
  await app.register(medicalHistoryRoutes);
  await app.register(odontogramRoutes);
  await app.register(treatmentPlanRoutes);
  await app.register(visitNotesRoutes);
  await app.register(periodontogramRoutes);
  await app.register(prescriptionRoutes);
  await app.register(consentRoutes);
  await app.register(evolutionTemplateRoutes);
  await app.register(medicalHistoryAuditRoutes);
  await app.register(patientSummaryRoutes);
  await app.register(odontogramVersionRoutes);
  await app.register(periodontogramVersionRoutes);
  await app.register(patientImageRoutes);
  await app.register(plaqueRecordRoutes);
  await app.register(agendaRoutes);
  await app.register(googleCalendarRoutes);
  await app.register(configuracionRoutes);
  await app.register(dentistRoutes);
  await app.register(treatmentTypeRoutes);
  await app.register(chairRoutes);
  await app.register(pipelineRoutes);
  await app.register(conversationRoutes);
  await app.register(adminRoutes);
  await app.register(whatsappRoutes);
  await app.register(whatsappTemplateRoutes);
  await app.register(notificationRoutes);
  await app.register(whatsappWebhookRoutes);
  await app.register(stripeWebhookRoutes);
  await app.register(mercadoPagoWebhookRoutes);
}
